# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  daily_newsletter:
    command: "Subscription.send_comic"
    queue: default
    schedule: 'every day at 5am'
  gap_checker:
    class: "ComicGapCheckerJob"
    queue: default
    schedule: 'every sunday at 4:30am'
  update_tree:
    command: "ComicImporter.call"
    queue: default
    schedule: 'every sunday at 1pm'

production:
  daily_newsletter:
    command: "Subscription.send_comic"
    queue: default
    schedule: 'every day at 5am'
  gap_checker:
    class: "ComicGapCheckerJob"
    queue: default
    schedule: 'every sunday at 4:30am'
  update_tree:
    command: "ComicImporter.call"
    queue: default
    schedule: 'every sunday at 4am'
